import type { Bus } from '../core/bus'
import { COLOR } from '../core/theme'
import type { ColorName } from '../core/theme'

/* ============================================================================
 * THE KEYBOARD MAP AND THE COLOUR LEGEND
 *
 * The legend is generated by walking COLOR itself, so it cannot drift from
 * what the city renders: a hue added to the palette appears here immediately,
 * with its key as its label until somebody writes down what it means. A legend
 * maintained by hand would eventually describe a city that no longer exists.
 * ==========================================================================*/

export interface Help {
  dispose(): void
}

interface KeyRow {
  /** Rendered as separate <kbd> elements. */
  k: string[]
  /** How the keys relate: pressed together, or alternatives. */
  j?: string
  d: string
}

interface KeySection {
  title: string
  rows: KeyRow[]
}

const KEYMAP: readonly KeySection[] = [
  {
    title: 'Camera',
    rows: [
      { k: ['Left-drag'], d: 'Pan in orbit mode — grab the ground and move it, the way a map does' },
      { k: ['Shift', 'Ctrl', 'Cmd'], j: ' or ', d: 'Hold and left-drag to orbit around the city' },
      { k: ['Wheel'], d: 'Zoom toward the cursor in orbit mode; adjust movement speed in fly mode' },
      { k: ['Right-click'], d: 'Context menu — also a long press on touch' },
      { k: ['W', 'A', 'S', 'D'], d: 'Move; the arrow keys do the same' },
      { k: ['Space', 'E'], j: ' / ', d: 'Rise in fly mode, jump on foot' },
      { k: ['C', 'Q'], j: ' / ', d: 'Descend in fly mode, crouch on foot' },
      { k: ['Shift', 'Alt'], j: ' · ', d: 'Boost · precision' },
      { k: ['1 finger', '2 fingers'], j: ' · ', d: 'Pan · pinch-zoom, twist to orbit, drag to tilt' },
      { k: ['Esc'], d: 'Leave pointer lock' },
    ],
  },
  {
    title: 'Moving around the city',
    rows: [
      { k: ['F', 'G'], j: ' · ', d: 'Fly · walk the city on foot at 1.7 m' },
      { k: ['H', 'Home', 'O'], j: ' · ', d: 'Establishing shot · default shot · straight-down overview' },
      { k: ['Click'], d: 'Select a building and open the inspector' },
      { k: ['Esc'], d: 'Close the inspector and clear the selection' },
    ],
  },
  {
    title: 'Reading and driving the cluster',
    rows: [
      { k: ['T'], d: 'Guided tour: one kubectl apply, followed the whole way' },
      { k: ['/', 'Ctrl-K', 'Cmd-K'], j: ' or ', d: 'Command palette — every component, knob and scenario' },
      { k: ['?'], d: 'This map' },
      { k: ['L', 'N'], j: ' · ', d: 'Toggle labels · toggle day and night' },
      { k: ['K', 'P'], j: ' or ', d: 'Pause and resume model time' },
      { k: [',', '.'], j: ' · ', d: 'Slower · faster' },
      { k: ['R'], d: 'Reset every knob to its default' },
    ],
  },
]

/**
 * What each colour is allowed to mean. Partial on purpose: a new entry in
 * COLOR still renders, labelled with its own key, rather than silently
 * disappearing from the legend.
 */
const MEANING: Partial<Record<ColorName, string>> = {
  desired: 'Desired state. A record in etcd — what you asked for. Always translucent, because a record is not a thing.',
  actual: 'Actual state. Matter: something that exists on a node right now.',
  api: 'kube-apiserver and the requests riding its pipeline.',
  etcd: 'etcd, the only durable truth in the cluster.',
  raft: 'The raft log: proposals, quorum acknowledgements, commits.',
  scheduler: 'kube-scheduler — filter, score, bind.',
  controller: 'Reconciliation. A controller closing the gap between desired and actual.',
  kubelet: 'kubelet and the node agents that report actual state back.',
  network: 'Services, EndpointSlices and the kube-proxy rule tables that realise them.',
  traffic: 'Requests in flight through the dataplane.',
  dns: 'CoreDNS name resolution.',
  ingress: 'The ingress controller and the load balancer at the cluster edge.',
  storage: 'PersistentVolumes, CSI attach and mount.',
  image: 'Image layers, the registry, and pulls.',
  ready: 'Ready. The readiness probe passes, so this pod may receive traffic.',
  pending: 'Pending. It exists in etcd and is not running yet — a verdict, not a queue position.',
  backoff: 'A retry timer is running: CrashLoopBackOff, ImagePullBackOff, a rate-limited workqueue.',
  failed: 'Failed. OOMKilled, Error, NotReady, or a request the API server refused.',
  terminating: 'Terminating. Inside the grace period, and already removed from every endpoint.',
  throttled: 'Throttled by the cgroup CPU quota. Slowed, never killed.',
  ground: 'Ground plane. Structure only.',
  groundDay: 'Ground plane in day mode.',
  deck: 'Decks and platforms. Structure only.',
  deckDay: 'Decks and platforms in day mode.',
  concrete: 'Building shells. Structure only.',
  concreteDay: 'Building shells in day mode.',
  edge: 'Edges, kerbs and rails. Structure only.',
  text: 'Labels and type.',
}

const GROUP: Partial<Record<ColorName, string>> = {
  desired: 'The one idea',
  actual: 'The one idea',
  api: 'Control plane',
  etcd: 'Control plane',
  raft: 'Control plane',
  scheduler: 'Control plane',
  controller: 'Control plane',
  kubelet: 'Control plane',
  network: 'Data plane',
  traffic: 'Data plane',
  dns: 'Data plane',
  ingress: 'Data plane',
  storage: 'Data plane',
  image: 'Data plane',
  ready: 'Health',
  pending: 'Health',
  backoff: 'Health',
  failed: 'Health',
  terminating: 'Health',
  throttled: 'Health',
  ground: 'Structure, which carries no meaning',
  groundDay: 'Structure, which carries no meaning',
  deck: 'Structure, which carries no meaning',
  deckDay: 'Structure, which carries no meaning',
  concrete: 'Structure, which carries no meaning',
  concreteDay: 'Structure, which carries no meaning',
  edge: 'Structure, which carries no meaning',
  text: 'Structure, which carries no meaning',
}

const GROUP_ORDER: readonly string[] = [
  'The one idea',
  'Control plane',
  'Data plane',
  'Health',
  'Structure, which carries no meaning',
  'Not yet described',
]

function hex(n: number): string {
  return `#${n.toString(16).padStart(6, '0')}`
}

function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  cls?: string,
  text?: string,
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag)
  if (cls) node.className = cls
  if (text !== undefined) node.textContent = text
  return node
}

export function createHelp(bus: Bus): Help {
  if (typeof document === 'undefined') return { dispose: () => {} }
  const host = document.getElementById('help')
  if (!host) {
    console.warn('[ui/help] #help is missing from the document; key map disabled')
    return { dispose: () => {} }
  }

  const scrim = el('div', 'ovl-scrim')
  const sheet = el('div', 'ovl-sheet help')
  sheet.setAttribute('role', 'dialog')
  sheet.setAttribute('aria-label', 'Input map and colour legend')

  const head = el('header', 'ovl-head')
  head.append(el('h2', 'ovl-title', 'Controls and colour'))
  const close = el('button', 'ovl-close', '✕')
  close.type = 'button'
  close.setAttribute('aria-label', 'Close')
  head.append(close)

  const scroll = el('div', 'ovl-scroll')

  /* ------------------------------------------------------------ the key map */

  const keys = el('div', 'help-keys')
  for (const section of KEYMAP) {
    const block = el('section', 'help-block')
    block.appendChild(el('h3', 'help-h', section.title))
    const table = el('div', 'help-table')
    for (const row of section.rows) {
      const line = el('div', 'help-row')
      const keyCell = el('div', 'help-kcell')
      for (let i = 0; i < row.k.length; i++) {
        if (i > 0) keyCell.appendChild(el('span', 'help-join', row.j ?? ' '))
        keyCell.appendChild(el('kbd', undefined, row.k[i]))
      }
      line.append(keyCell, el('div', 'help-d', row.d))
      table.appendChild(line)
    }
    block.appendChild(table)
    keys.appendChild(block)
  }

  /* ------------------------------------------------------------ the legend */

  const legend = el('div', 'help-legend')
  legend.appendChild(el('h3', 'help-h', 'Colour is semantic, never decorative'))
  legend.appendChild(
    el(
      'p',
      'help-note',
      'Every swatch below is read straight out of the palette the city renders with. At night, structure is matte and meaning glows; only an emissive above 1.0 crosses the bloom threshold, so a glow always carries information.',
    ),
  )

  const buckets = new Map<string, ColorName[]>()
  const names = Object.keys(COLOR) as ColorName[]
  for (const name of names) {
    const group = GROUP[name] ?? 'Not yet described'
    const bucket = buckets.get(group)
    if (bucket) bucket.push(name)
    else buckets.set(group, [name])
  }
  /* Fixed order first, then any group the palette grew that nobody has filed. */
  const groups: string[] = []
  for (const g of GROUP_ORDER) if (buckets.has(g)) groups.push(g)
  for (const g of buckets.keys()) if (!groups.includes(g)) groups.push(g)

  for (const group of groups) {
    const block = el('section', 'help-block')
    block.appendChild(el('h4', 'help-sub', group))
    const grid = el('div', 'help-swatches')
    for (const name of buckets.get(group) ?? []) {
      const value = COLOR[name]
      const item = el('div', 'help-swatch')
      const chip = el('span', 'help-chip')
      chip.style.background = hex(value)
      const body = el('div', 'help-swatch-body')
      body.append(
        el('span', 'help-swatch-name', name),
        el('span', 'help-swatch-desc', MEANING[name] ?? 'No meaning has been written for this colour yet.'),
      )
      item.append(chip, body, el('code', 'help-swatch-hex', hex(value)))
      grid.appendChild(item)
    }
    block.appendChild(grid)
    legend.appendChild(block)
  }

  const footer = el(
    'p',
    'help-foot',
    'K8Skylines is a model, not an emulator. No Kubernetes code runs in this page; durations are scaled so a person can watch them, and every simplification that could change the lesson is written into the inspector for the mechanism it affects.',
  )

  scroll.append(keys, legend, footer)
  sheet.append(head, scroll)
  host.append(scrim, sheet)
  host.hidden = true

  /* ------------------------------------------------------------------ open */

  let isOpen = false

  const setOpen = (next: boolean): void => {
    if (next === isOpen) return
    isOpen = next
    host.hidden = !next
    bus.emit('overlay', { id: 'help', open: next })
    if (next) scroll.scrollTop = 0
  }

  const onClick = (ev: MouseEvent): void => {
    const target = ev.target
    if (target === scrim || target === close) setOpen(false)
  }
  host.addEventListener('click', onClick)

  const typing = (ev: KeyboardEvent): boolean => {
    const t = ev.target
    if (!(t instanceof HTMLElement)) return false
    return t.isContentEditable || t.tagName === 'INPUT' || t.tagName === 'TEXTAREA'
  }

  const onKey = (ev: KeyboardEvent): void => {
    if (typing(ev)) return
    if (isOpen && ev.key === 'Escape') {
      ev.preventDefault()
      ev.stopPropagation()
      setOpen(false)
      return
    }
    if (!isOpen && ev.key === '?') {
      ev.preventDefault()
      ev.stopPropagation()
      setOpen(true)
    }
  }
  window.addEventListener('keydown', onKey, true)

  const offOverlay = bus.on('overlay', (p) => {
    if (p.id === 'help') setOpen(p.open)
    else if (p.open && (p.id === 'search' || p.id === 'tour')) setOpen(false)
  })

  return {
    dispose(): void {
      offOverlay()
      host.removeEventListener('click', onClick)
      window.removeEventListener('keydown', onKey, true)
      host.textContent = ''
      host.hidden = true
      isOpen = false
    },
  }
}
